export const serviceTemplates = [
    { name: 'Proxmox', defaultPort: 8006, icon: 'proxmox', category: 'Infrastructure' },
    { name: 'Portainer', defaultPort: 9000, icon: 'portainer', category: 'Infrastructure' },
    { name: 'Docker', defaultPort: 2375, icon: 'docker', category: 'Infrastructure' },
    { name: 'Nginx', defaultPort: 80, icon: 'nginx', category: 'Web Server' },
    { name: 'Nginx Proxy Manager', defaultPort: 81, icon: 'nginx', category: 'Web Server' },
    { name: 'Traefik', defaultPort: 8080, icon: 'traefik', category: 'Web Server' },
    { name: 'MariaDB', defaultPort: 3306, icon: 'mariadb', category: 'Database' },
    { name: 'PostgreSQL', defaultPort: 5432, icon: 'postgresql', category: 'Database' },
    { name: 'MySQL', defaultPort: 3306, icon: 'mysql', category: 'Database' },
    { name: 'Redis', defaultPort: 6379, icon: 'redis', category: 'Database' },
    { name: 'MongoDB', defaultPort: 27017, icon: 'mongodb', category: 'Database' },
    { name: 'Home Assistant', defaultPort: 8123, icon: 'homeassistant', category: 'Smart Home' },
    { name: 'Node-RED', defaultPort: 1880, icon: 'nodered', category: 'Smart Home' },
    { name: 'Plex', defaultPort: 32400, icon: 'plex', category: 'Media' },
    { name: 'Jellyfin', defaultPort: 8096, icon: 'jellyfin', category: 'Media' },
    { name: 'Emby', defaultPort: 8096, icon: 'emby', category: 'Media' },
    { name: 'Sonarr', defaultPort: 8989, icon: 'sonarr', category: 'Media' },
    { name: 'Radarr', defaultPort: 7878, icon: 'radarr', category: 'Media' },
    { name: 'Grafana', defaultPort: 3000, icon: 'grafana', category: 'Monitoring' },
    { name: 'Prometheus', defaultPort: 9090, icon: 'prometheus', category: 'Monitoring' },
    { name: 'Uptime Kuma', defaultPort: 3001, icon: 'uptimekuma', category: 'Monitoring' },
    { name: 'Pi-hole', defaultPort: 80, icon: 'pihole', category: 'Network' },
    { name: 'AdGuard Home', defaultPort: 3000, icon: 'adguard', category: 'Network' },
    { name: 'Nextcloud', defaultPort: 443, icon: 'nextcloud', category: 'Storage' },
    { name: 'Syncthing', defaultPort: 8384, icon: 'syncthing', category: 'Storage' },
    { name: 'Paperless-ngx', defaultPort: 8000, icon: 'paperless', category: 'Documents' },
    { name: 'Vaultwarden', defaultPort: 8080, icon: 'vaultwarden', category: 'Security' },
    { name: 'Authentik', defaultPort: 9000, icon: 'authentik', category: 'Security' },
    { name: 'GitLab', defaultPort: 80, icon: 'gitlab', category: 'Development' },
    { name: 'Gitea', defaultPort: 3000, icon: 'gitea', category: 'Development' },
    { name: 'VS Code Server', defaultPort: 8443, icon: 'vscode', category: 'Development' },
]
